// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package documentgeneration.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import documentgeneration.implementation.TokenManager;

public class JA_Token_Request extends CustomJavaAction<IMendixObject>
{
	private final documentgeneration.proxies.Enum_DeploymentType deploymentType;
	private final java.lang.String appId;
	private final java.lang.String personalAccessToken;
	private final java.lang.String applicationUrl;

	public JA_Token_Request(
		IContext context,
		java.lang.String _deploymentType,
		java.lang.String _appId,
		java.lang.String _personalAccessToken,
		java.lang.String _applicationUrl
	)
	{
		super(context);
		this.deploymentType = _deploymentType == null ? null : documentgeneration.proxies.Enum_DeploymentType.valueOf(_deploymentType);
		this.appId = _appId;
		this.personalAccessToken = _personalAccessToken;
		this.applicationUrl = _applicationUrl;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		return TokenManager.requestAccessToken(getContext(), deploymentType, appId, personalAccessToken, applicationUrl);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Token_Request";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
